apiVersion: apps/v1
kind: Deployment
metadata:
  name: protfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: protfolio
  template:
    metadata:
      labels:
        app: protfolio
    spec:
      containers:
      - name: protfolio
        image: protfolio:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
